# Generated by Django 3.2.12 on 2023-02-14 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookrenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 12, 59, 56, 194869)),
        ),
    ]
