# Generated by Django 4.1.6 on 2023-02-15 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 11, 44, 20, 167015)),
        ),
    ]
