# Generated by Django 4.1.6 on 2023-02-15 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_image_alter_bookrenthistory_back_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 12, 59, 7, 671561)),
        ),
    ]
