# Generated by Django 4.1.6 on 2023-02-16 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_remove_category_name_alter_bookrenthistory_back_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nameofcategory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 9, 26, 52, 538301)),
        ),
    ]
