# Generated by Django 4.1.6 on 2023-02-16 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_remove_category_nameofcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 10, 59, 7, 300321)),
        ),
    ]
