# Generated by Django 4.1.6 on 2023-02-16 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_alter_bookrenthistory_back_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 11, 11, 18, 24058)),
        ),
    ]
